### ISSUE TITLE
LCC dangerous junctions map not working

### ISSUE THREAD

**Issue by neilchristiex** [londoncyclingcampaign/lcc-dangerous-junctions#61]
Map doesn't work. 
I get the error message: 

Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/londoncyclingcampaign/lcc-dangerous-junctions/issues/new).

This has been happening yesterday and today, using chrome and safari, on iPhone and Mac.

**Comment by danielhills** [comment]
Thanks for reporting - I’ve rebooted and it should be working again now.
